### ISSUE TITLE
Parsing error in package.json

### ISSUE THREAD

**Issue by ikkisoft** [doyensec/electronegativity#38]
**Describe the bug**
Parsing error in package.json - **Unexpected token I in JSON at position 0**

**To Reproduce**
1. Clone Atom https://github.com/atom/atom
2. Try to scan it

**Stacktraces**
```
Tolerable error parsing /Users/ikki/Downloads/atom/resources/win/atom.js - Line 5: Variable name may not be eval or arguments in strict mode
Error parsing /Users/ikki/Downloads/atom/spec/fixtures/typescript/invalid.ts - Unexpected token, expected ";" (1:14)
Error parsing /Users/ikki/Downloads/atom/spec/fixtures/packages/package-with-broken-package-json/package.json - Unexpected token I in JSON at position 0
(node:25462) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'chars' of undefined
    at Cell.mergeTableOptions (/Users/ikki/Downloads/electronegativity/node_modules/cli-table2/src/cell.js:37:33)
    at /Users/ikki/Downloads/electronegativity/node_modules/cli-table2/src/table.js:29:12
    at arrayEach (/Users/ikki/Downloads/electronegativity/node_modules/cli-table2/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/ikki/Downloads/electronegativity/node_modules/cli-table2/node_modules/lodash/lodash.js:9344:14)
    at /Users/ikki/Downloads/electronegativity/node_modules/cli-table2/src/table.js:28:7
    at arrayEach (/Users/ikki/Downloads/electronegativity/node_modules/cli-table2/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/ikki/Downloads/electronegativity/node_modules/cli-table2/node_modules/lodash/lodash.js:9344:14)
    at Table.toString (/Users/ikki/Downloads/electronegativity/node_modules/cli-table2/src/table.js:27:5)
    at run (/Users/ikki/Downloads/electronegativity/dist/runner.js:208:23)
(node:25462) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25462) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ikkisoft** [comment]
A quick update since my local installation was probably broken. The app is not terminating, but I still get the following warnings:

```
Tolerable error parsing /Users/ikki/Downloads/atom/resources/win/atom.js - Line 5: Variable name may not be eval or arguments in strict mode
Error parsing /Users/ikki/Downloads/atom/spec/fixtures/typescript/invalid.ts - Unexpected token, expected ";" (1:14)
Error parsing /Users/ikki/Downloads/atom/spec/fixtures/packages/package-with-broken-package-json/package.json - Unexpected token I in JSON at position 0
```

As mentioned, scan is anyway completed.

**Comment by JarLob** [comment]
As a side note please notice the directory name of the third error :)

**Comment by ikkisoft** [comment]
The first stack trace was generated by having a too recent version of lodash for cli-table2 (in order to fix stuff from npm audit). Reverted.

As long as the app doesn't crash (and it does not) the current warning/mechanism is good, and it's ok to have those errors in the console.

Closing this non-issue.

**Comment by JarLob** [comment]
My smiley was about the fact the json file is broken on purpose.

**Comment by ikkisoft** [comment]
Got it. In fact I didn't notice it when I first opened the issue.
